baseURL: "https://modulandu.com/"
title: Modulandu
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
googleAnalytics: UA-171032865-1

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        profileMode:
            enabled: true
            title: We are Modulandu
            imageUrl: "logomodulandu1.png"
            imageTitle: logo
            imageWidth: 120
            imageHeight: 120
            #subtitle: "☄️ chill | ☁️ ambient | 🌙 electronic | 📱 good vibrations"
            subtitle: "
            Sounds modulate our mood and our senses, they make our body move and our emotions flow.<br><br>
            Modulandu is a collective project that unites artists to produce music in a way that is <i>independent</i>, <i>creative</i> and <i>visceral</i>.<br><br>
            Listen and follow us on our channels.
            Buy our music on <a href=\"https://modulandu.bandcamp.com\">Bandcamp</a>.<br>
            With your support we can spend more time making the music you enjoy.
            <br><br>
            ☄️ poetry | ☁️ rhythm | 📱 culture | 🌙 good vibes"
            buttons:
                - name: Blog
                  url: posts
                - name: Tags
                  url: tags
        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10
                - name: Categories
                  url: categories/
                  weight: 10

    pt-br:
        languageName: "Português"
        languageAltTitle: PT-BR
        weight: 2
        title: Modulandu
        profileMode:
            enabled: true
            title: Somos Modulandu
            imageUrl: "logomodulandu1.png"
            imageTitle: logo
            imageWidth: 120
            imageHeight: 120
            subtitle: "Sons modulam o nosso humor e os nossos sentidos, fazem nosso corpo se mover e nossas emoções fluírem.<br><br>
            Modulandu é um projeto coletivo que une artistas para produzir música de forma <i>independente</i>, <i>autêntica</i> e <i>visceral</i>.<br><br>
            Ouça e siga a gente pelos nossos canais. Compre a nossa música pelo <a href=\"https://modulandu.bandcamp.com\">Bandcamp</a>.<br>
            Com o seu apoio podemos dedicar mais tempo para criar a música que você gosta.<br>
            <br><br>
            ☄️ poesia | ☁️ ritmo | 📱 cultura | 🌙 good vibes"
            #subtitle: "Música pode ser modulada de diversas maneiras: 
            #rítmica e harmonicamente, mas também histórica e culturalmente. 
            #Sons modulam o nosso humor e os nossos sentidos, fazem nosso corpo 
            #se mover e nossas emoções fluírem."
            buttons:
                - name: Blog
                  url: posts
                - name: Tags
                  url: tags
        menu:
            main:
                - name: Posts
                  url: archives/
                  weight: 5
                - name: Tags
                  url: tags
                  weight: 10
                - name: Categorias
                  url: categories
                  weight: 10


outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Modulandu"
    author: ["Fernando Filho", "Lucas Jardim"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: false
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    # comments: false
    images: ["papermod-cover.png"]

    profileMode:
        enabled: enabled
        title: Modulandu
        imageUrl: "#"
        imageTitle: Modulandu
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "Modulandu"
        Content: >
            Music can be modulated in several ways:
            rhythmically and harmonically, but also historically and culturally.
            Sounds modulate our mood and our senses, they make our
            body move and our emotions flow.<br><br>
            
            We collaborate with other artists to make the music we love.
            Join us in this journey.

    socialIcons:
        - name: bandcamp
          url: "https://modulandu.bandcamp.com"
        - name: soundcloud
          url: "https://soundcloud.com/modulandu"
        - name: instagram
          url: "https://instagram.com/modulandu"
        - name: mixcloud
          url: "https://mixcloud.com/modulandu"
        - name: RsS
          url: "index.xml"

    editPost:
        URL: "https://github.com/modulandu/modulandu/tree/main/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

   # analytics:
   #      google:
   #          SiteVerificationTag: "XYZabc"

    # assets:
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
